name: "Chonkbot"
description: "How chonky are your pull requests?"
author: "Tom Bowden"

inputs:
  token:
    description: GitHub token
    required: true

outputs:
  chonkLevel:
    description: Plaintext summary of PR's c (i.e. one dimensional position within the chonk landscape)

runs:
  using: "node12"
  main: "dist/index.js"

branding:
  color: orange
  icon: package
